#!/usr/bin/env python

import os
import sys

import rospkg
import rospy

from python_qt_binding import loadUi
from python_qt_binding.QtWidgets import QApplication, QWidget

from academy_py.service import SelectJointService

class CommanderWidget(QWidget):
    def __init__(self):
        super(CommanderWidget, self).__init__()

        self.srv = SelectJointService()

        uifile = os.path.join(rospkg.RosPack().get_path('academy_commander'), 'resource', 'commander.ui')
        loadUi(uifile, self)
        self.select.clicked.connect(self.handleClick)

    def handleClick(self):
        res = self.srv.select_joint(self.joint_name.text(), 1.0)
        self.success.setText(str(res))

if __name__ == '__main__':
    rospy.init_node('academy_commander', anonymous=True)
    app = QApplication(sys.argv)
    w = CommanderWidget()
    w.show()
    sys.exit(app.exec_())
